services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    tty: true
    environment:
      - NEO4J_DB_USER=$NEO4J_DB_USER
      - NEO4J_DB_PASSWORD=$NEO4J_DB_PASSWORD
      - NEO4J_DB_URI=$NEO4J_DB_URI
    volumes:
      - ./src:/home/nonroot/app/src
      - ./pyproject.toml:/home/nonroot/app/pyproject.toml
      - ./uv.lock:/home/nonroot/app/uv.lock
    ports:
      - ${FASTAPI_SERVER_PORT}:8000
      - 3001:3001
      - 8006:8006
    depends_on:
      - neo4j
  
  neo4j:
    image: neo4j:2025-bullseye
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/config:/config
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=$NEO4J_DB_USER/$NEO4J_DB_PASSWORD
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
volumes:
  open-webui: